#!/usr/bin/python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate the tray icons by re-painting the symbolic icon.

The geometry lives in data/icons/hicolor/symbolic/apps/cipher-symbolic.svg and
is documented there; this only re-paints it. Reading that file rather than
re-declaring the shapes means the mark cannot drift between the tray and the
rest of the application, which is the failure mode a second copy of the path
data would invite.

The symbolic icon is the right source even though these are not symbolic icons
themselves. A tray pixmap is sent to the panel as pixels and never recoloured
by the host, so each colour has to be baked into a file of its own -- which is
exactly what a fill-only monochrome drawing makes trivial.

The colours match tools/generate-icons.py in the Cipher Bridge tree, so a tray
icon set to Blue is the same blue as the browser toolbar icon. They are
duplicated rather than shared because the two are separately packaged, and the
application is the one that owns the choice -- it is what sends the colour to
the extension.

    tools/generate-tray-icons.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ICONS = Path(__file__).resolve().parent.parent / "data" / "icons" / "hicolor"
TEMPLATE = ICONS / "symbolic" / "apps" / "cipher-symbolic.svg"
OUTPUT = ICONS / "scalable" / "apps"

# The fill the symbolic icon is drawn in, and so the string being replaced.
DEFAULT = "#2e3436"

# The template's title, replaced so a tray icon does not claim to be the
# symbolic one, and so there is somewhere to say where these files come from.
# It has to stay below the root element: everything the template says about
# gdk-pixbuf sniffing the leading bytes applies to these files too, since
# flatpak exports and validates every icon whose name starts with the
# application ID, tray icons included.
TITLE = "<title>Cipher symbolic</title>"
HEADER = """<title>Cipher tray</title>
  <!--
    Generated by tools/generate-tray-icons.py, which re-paints the symbolic
    icon rather than redrawing it. Edits here are lost the next time it runs;
    change the symbolic icon instead. The notes below are the template's own
    and describe that file.
  -->"""

# The colour the unsuffixed fallback below is painted in. Also the brand pink,
# which is why "pink" in the table repeats it.
FALLBACK = "#ff67ef"

# Every value except the pink is libadwaita's own named palette (the -4 shades),
# which is what the application already uses for entry labels. Sharing them
# means the icon colours and the label colours agree exactly.
COLOURS = {
    "pink": FALLBACK,
    "blue": "#1c71d8",
    "green": "#2ec27e",
    "yellow": "#f5c211",
    "orange": "#e66100",
    "red": "#c01c28",
    "purple": "#813d9c",
    "brown": "#865e3c",
    # A tray pixmap is sent as pixels and never recoloured by the panel, so
    # monochrome has to commit to one shade rather than adapting like a symbolic
    # icon would. White, because a dark panel is overwhelmingly the common case.
    # It is the one entry with no good answer for the other case: the mark is
    # thin outline work now rather than the solid square it used to be, so on a
    # light panel white leaves very little to see. Anyone on a light panel is
    # better served by any of the accents above.
    "monochrome": "#fcfcfc",
    # Not a selectable colour: the state a locked safe takes, whatever colour is
    # chosen. The same dull grey the browser extension uses for its own locked
    # icon, so the two agree. It cannot be the monochrome icon above -- that one
    # is white, so "locked" would have been white rather than grey for every
    # accent, and identical to the icon itself for anyone on Monochrome.
    "locked": "#90949b",
}


def main() -> int:
    template = TEMPLATE.read_text()
    for marker in (DEFAULT, TITLE):
        if marker not in template:
            print(f"{TEMPLATE} no longer contains {marker}", file=sys.stderr)
            return 1

    template = template.replace(TITLE, HEADER)

    # The unsuffixed icon, installed as the fallback for a colour setting this
    # build has no file for. Written first so a mistake in the table below
    # cannot leave the tray with no icon at all.
    written = [("cipher-tray.svg", FALLBACK)]
    written += [(f"cipher-tray-{name}.svg", colour) for name, colour in COLOURS.items()]

    for name, colour in written:
        (OUTPUT / name).write_text(template.replace(DEFAULT, colour))
        print(f"{name}: {colour}")

    print(f"\n{len(written)} files written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
